---
- hosts: all
  become: true
  roles:
      - { role: 'common', tags: 'common' }
      - { role: 'iptables', tags: 'iptables' }

- hosts: datacenter
  roles:
    - { role: hw, when: facter_is_virtual == "false" , tags: 'hw'}
    - { role: monitoring-client, when: "'monitoring' not in group_names", tags: 'monitoring-client'}
    - { role: postfix-satellite, when: "'mailserver' not in group_names", tags: 'postfix-client'}
- hosts: monitoring
  roles:
    - { role: 'monitoring-server', tags: 'monitoring-server' }
- hosts: hypervisor
  roles:
    - { role: 'hypervisor', tags: 'hypervisor' }
- hosts: froxlor
  roles:
    - { role: 'froxlor', tags: 'froxlor' }
