---
- hosts: all
  become: true
  roles:
      - common
      - { role: 'iptables', tags: 'iptables' }

- hosts: datacenter
  roles:
    - { role: hw, when: facter_is_virtual == "false" }
    - { role: monitoring-client, when: "'monitoring' not in group_names" }
    - { role: postfix-satellite, when: "'mailserver' not in group_names" }
- hosts: monitoring
  roles:
    - monitoring-server
- hosts: hypervisor
  roles:
    - hypervisor
- hosts: froxlor
  roles:
    - froxlor
