- name: preseed phpmyadmin
  debconf:
    name: phpmyadmin
    question: phpmyadmin/{{ item.question }}
    vtype: {{ item.vtype }}
    value: {{ item.value }}
  with_items:
    - { question: reconfigure-webserver, vtype: multiselect, value: apache2 }
    - { question: mysql/admin-pass, vtype: password, value: "{{ mysql_root_password }}" }
  when: mycnf_file.stat.exists == false

- name: apache2
  apt: pkg={{ item }} install_recommends=no state=present
  with_items:
    - apache2
    - libapache2-mod-php5
    - phpmyadmin
    - php5-gd
    - php5-imap
    - php5-curl
