- name: Add froxlor Key
  apt_key:
    id: FD88018B6F2D5390D051343FF6B4A8704F9E9BBC
    state: present
    keyserver: pool.sks-keyservers.net

- name: Add froxlor Repository
  apt_repository:
    repo: 'deb http://debian.froxlor.org/ {{ ansible_distribution_release }} main' state=present
