- name: Add debmon Key
  apt_key:
    url: https://debmon.org/debmon/repo.key
    state: present

- name: Add debmon repository
  apt_repository:
    repo: deb https://debmon.org/debmon debmon-jessie main
    state: present
    update_cache: yes

- name: install Icinga and dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - icinga2
    - monitoring-plugins
    - icinga2-ido-mysql
    - apache2
    - python-mysqldb

- name: Set apache iptables
  iptables_raw:
    name: allow_apache
    weight: 50
    keep_unmanaged: '{{ iptables_keep_unmanaged }}'
    state: present
    rules: |
      -A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
      -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT

- name: Add Mysql Database
  mysql_db:
    name: icinga
    state: present
  register: icinga_db_created

- name: Import Mysql Database
  mysql_db:
    name: icinga
    target: /usr/share/icinga2-ido-mysql/schema/mysql.sql
    state: import
  when: icinga_db_created.changed

- name: Add MySQL User
  mysql_user:
    name: icinga
    password: "{{ icinga_mysql_password }}"
    priv: icinga.*:ALL
    append_privs: yes

- name: Add ido-mysql Configuration
  template:
    src: ido-mysql.conf.j2
    dest: /etc/icinga2/features-available/ido-mysql.conf
    mode: 0600
    owner: nagios
    group: nagios
  become: true
  notify:
    - restart icinga2

- name: Enable ido-mysql
  command: icinga2 feature enable ido-mysql
  args:
    creates: /etc/icinga2/features-enabled/ido-mysql.conf
  notify:
    - restart icinga2

- name: Check if api-users file already exists.
  stat:
    path: /etc/icinga2/conf.d/api-users.conf
  register: apiusers_file
  changed_when: False

- name: add default API Users
  template:
    src: api-users.conf
    dest: /etc/icinga2/conf.d/api-users.conf
    owner: root
    mode: 0666
  when: apiusers_file.stat.exists == false
  notify:
    - restart icinga2

- name: Enable api
  command: icinga2 api setup
  args:
    creates: /etc/icinga2/features-enabled/api.conf
  notify:
    - restart icinga2

- name: Set api iptables
  iptables_raw:
    name: allow_icinga_api
    weight: 50
    keep_unmanaged: '{{ iptables_keep_unmanaged }}'
    state: present
    rules: "-A INPUT -p tcp -m tcp --dport 5665 -j ACCEPT"
