- name: Add debmon Key
  apt_key:
    url: https://packages.icinga.com/icinga.key
    state: present

- name: Add debmon repository
  apt_repository:
    repo: "deb http://packages.icinga.com/debian icinga-{{ ansible_distribution_release}} main"
    state: present
    update_cache: yes

- name: install Icinga and dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - icinga2
    - monitoring-plugins
    - monitoring-plugins-standard

- name: Enable api
  command: icinga2 api setup
  args:
    creates: /etc/icinga2/features-enabled/api.conf
  become: true
  notify:
    - restart icinga2

- name: Set api iptables
  iptables_raw:
    name: allow_icinga_api
    weight: 50
    keep_unmanaged: yes
    state: present
    rules: "-A INPUT -p tcp -m tcp --dport 5665 -j ACCEPT"
