# Install basic apps and remove harmful/unneeded apps


- name: Install common software
  apt: name={{ item }} state=present
  with_items:
    - apt-rdepends
    - apt-transport-https
    - at
    - bash-completion
    - ca-certificates
    - ethtool
    - facter
    - git
    - hdparm
    - heirloom-mailx
    - haveged
    - htop
    - iotop
    - iputils-tracepath
    - libwww-perl
    - locate
    - mawk
    - mc
    - molly-guard
    - multitail
    - mtr
    - netcat-openbsd
    - net-tools
    - nmap
    - ntpdate
    - openssh-blacklist
    - openssh-blacklist-extra
    - postfix
    - psmisc
    - subversion
    - sudo
    - tcpdump
    - telnet
    - time
    - tmux
    - tree
    - vim
    - w3m
    - whois
    - zsh

- name: Remove harmful / unneeded
  apt: name={{ item }} state=absent
  with_items:
    - ftp
    - exim
