- name: Install security software
  apt: name={{ item }} state=present
  with_items:
    - openssh-server
    - ebtables

- name: Install plattform specific security packages
  apt:
    name: "{{ item.key }}"
    state: latest
  when: ansible_distribution == item.value
  with_dict:
    openssh-blacklist: Debian
    openssh-blacklist-extra: Debian

- name: No Root Login
  lineinfile:
    dest=/etc/ssh/sshd_config
    state=present
    regexp='^PermitRootLogin'
    line='PermitRootLogin {{ sshd_permit_root_login}}'
  notify:
    - restart ssh
